language: ruby

gemfile:
  - gemfiles/Gemfile.rails42
  - gemfiles/Gemfile.rails50
  - gemfiles/Gemfile.rails51

rvm:
  - 2.2.5
  - 2.3.1

sudo: false

cache: bundler

before_script: "bundle update"

script:
  - bundle exec rake test
  # - bundle exec rubocop .
