language: ruby

gemfile:
  - gemfiles/Gemfile.rails42
  - gemfiles/Gemfile.rails50

rvm:
  - 2.2.5
  - 2.3.1

sudo: false

cache: bundler

before_script: "bundle update"

script:
  - rm -f test/dummy/db/test.sqlite3 # Rails 4->5 issue
  - bundle exec rake test
  - bundle exec rubocop .
